import csv
import io
import json
import os
import re
from datetime import datetime
from urllib.parse import quote

from fastapi.responses import StreamingResponse
from fpdf import FPDF

# ─── Label translations ───────────────────────────────────────────────────────
_LABELS = {
    "en": {
        "report_title": "GeoRank Report",
        "analysis_title": "GeoRank Statistical Analysis Report",
        "summary": "Summary",
        "total_checks": "Total Checks",
        "mention_rate": "Mention Rate",
        "avg_score": "Average Score",
        "trend": "Trend",
        "engine": "Engine",
        "query": "Query",
        "mentioned": "Mentioned",
        "position": "Position",
        "word_count": "Word Count",
        "score": "Score",
        "citation": "Citation",
        "checked_at": "Checked At",
        "yes": "Yes",
        "no": "No",
        "reports": "Reports",
        "total_queries": "Total Queries",
        "overall_mention_rate": "Overall Mention Rate",
        "overall_avg_score": "Overall Avg Score",
        "engine_consistency": "Engine Consistency",
        "engine_summary": "Engine Summary",
        "mention_count": "Mention Count",
        "total_samples": "Total Samples",
        "avg_position": "Avg Position",
        "avg_word_count": "Avg Word Count",
        "citations": "Citations",
        "brand": "Brand",
        "generated_at": "Generated At",
        "sample_count": "Sample Count",
        "report_type": "Report Type",
        "type_visibility": "Visibility Report",
        "type_statistical": "Statistical Analysis",
        "generated_by": "Generated by GeoRank",
    },
    "zh": {
        "report_title": "GeoRank 报告",
        "analysis_title": "GeoRank 统计分析报告",
        "summary": "概要",
        "total_checks": "检测总数",
        "mention_rate": "提及率",
        "avg_score": "平均评分",
        "trend": "趋势",
        "engine": "引擎",
        "query": "查询词",
        "mentioned": "提及",
        "position": "位置",
        "word_count": "词数",
        "score": "评分",
        "citation": "引用",
        "checked_at": "检测时间",
        "yes": "是",
        "no": "否",
        "reports": "检测记录",
        "total_queries": "总查询数",
        "overall_mention_rate": "总体提及率",
        "overall_avg_score": "总体平均评分",
        "engine_consistency": "引擎一致性",
        "engine_summary": "引擎概要",
        "mention_count": "提及次数",
        "total_samples": "总采样数",
        "avg_position": "平均位置",
        "avg_word_count": "平均词数",
        "citations": "引用内容",
        "brand": "品牌",
        "generated_at": "生成时间",
        "sample_count": "采样数",
        "report_type": "报告类型",
        "type_visibility": "可见度报告",
        "type_statistical": "统计分析",
        "generated_by": "由 GeoRank 生成",
    },
}

# ─── Constants ────────────────────────────────────────────────────────────────
_FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"

# PDF color palette (matches design system)
_COLOR_HEADER_BG = (76, 110, 245)     # brand-500 #4c6ef5
_COLOR_HEADER_FG = (255, 255, 255)    # white
_COLOR_META_BG = (241, 243, 245)      # surface-2 #f1f3f5
_COLOR_META_FG = (108, 117, 125)      # text-secondary #6c757d
_COLOR_ROW_ALT = (248, 249, 250)      # surface-1 #f8f9fa
_COLOR_BORDER = (233, 236, 239)       # surface-3 #e9ecef
_COLOR_TEXT = (33, 37, 41)            # text-primary #212529
_COLOR_KPI_VALUE = (76, 110, 245)     # brand-500
_COLOR_FOOTER = (173, 181, 189)       # text-tertiary #adb5bd


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _content_disposition(filename: str) -> str:
    encoded = quote(filename)
    return f"attachment; filename*=UTF-8''{encoded}"


def _L(lang: str, key: str) -> str:
    return _LABELS.get(lang, _LABELS["en"]).get(key, key)


# Characters that fpdf2 cannot measure/render — causes "Not enough horizontal space"
_BAD_CHARS_RE = re.compile(
    '['
    '--'  # control chars (keep \t \n \r)
    '​-‏'                              # zero-width spaces, LTR/RTL marks
    '  '                               # line/paragraph separators
    '‪-‮'                              # bidi overrides
    '⁠-⁩'                              # word joiners, invisible operators
    '⁪-⁯'                              # symmetric swapping, Arabic forms
    '﷐-﷯'                              # non-characters
    '﻿'                                     # BOM (zero-width no-break space)
    '￾￿'                               # non-characters
    '\ud800-\udfff'                              # surrogates
    ']'
)


def _sanitize_for_pdf(text: str) -> str:
    """Remove characters that fpdf2 cannot render. Preserves all readable content."""
    text = _BAD_CHARS_RE.sub('', text)
    text = text.replace('\x00', '')
    return text


def _insert_breaks(text: str, every: int = 30) -> str:
    """Insert regular spaces into long unbreakable segments so fpdf2 can wrap."""
    def _break_match(m: re.Match) -> str:
        s = m.group(0)
        if len(s) <= every:
            return s
        return " ".join(s[i:i + every] for i in range(0, len(s), every))
    return re.sub(r'\S{' + str(every) + r',}', _break_match, text)


def _safe_multi_cell(pdf: FPDF, w: float, h: float, text: str):
    """Render full text via multi_cell. Sanitizes problematic Unicode, never truncates."""
    clean = _sanitize_for_pdf(text or "")
    if not clean.strip():
        return
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(w, h, _insert_breaks(clean, 30))


def _now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def _csv_response(csv_text: str, filename: str) -> StreamingResponse:
    """Wrap CSV text with UTF-8 BOM and return as StreamingResponse."""
    payload = "﻿" + csv_text
    return StreamingResponse(
        iter([payload.encode("utf-8")]),
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": _content_disposition(filename)},
    )


# ─── PDF subclass with footer ─────────────────────────────────────────────────

class _GeoRankPDF(FPDF):
    """FPDF subclass that adds page footer with branding and page numbers."""

    def __init__(self, lang: str = "en", **kwargs):
        super().__init__(**kwargs)
        self._lang = lang

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_COLOR_FOOTER)
        self.cell(0, 8, _L(self._lang, "generated_by"), align="L")
        self.cell(0, 8, f"{self.page_no()}/{{nb}}", align="R")


def _init_pdf(lang: str, orientation: str = "L") -> tuple[_GeoRankPDF, str, str]:
    """Create PDF with Chinese font support. Returns (pdf, font_normal, font_bold)."""
    pdf = _GeoRankPDF(lang=lang, orientation=orientation, format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    use_cjk = os.path.exists(_FONT_PATH)
    if use_cjk:
        pdf.add_font("SimHei", "", _FONT_PATH, uni=True)
        pdf.add_font("SimHei", "B", _FONT_PATH, uni=True)
        return pdf, "SimHei", "SimHei"
    return pdf, "Helvetica", "Helvetica"


def _draw_metadata_bar(pdf: _GeoRankPDF, fn: str, fb: str, fields: list[tuple[str, str]]):
    """Draw a gray metadata bar with key-value pairs."""
    pdf.set_font(fb, "B", 10)
    pdf.set_fill_color(*_COLOR_META_BG)
    pdf.set_text_color(*_COLOR_META_FG)
    bar_w = pdf.w - pdf.l_margin - pdf.r_margin
    pdf.cell(bar_w, 8, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_y(pdf.get_y() - 8)
    col_w = bar_w / len(fields)
    for label, value in fields:
        x = pdf.get_x()
        pdf.set_font(fn, "", 8)
        pdf.set_text_color(*_COLOR_META_FG)
        pdf.set_xy(x, pdf.get_y())
        pdf.cell(col_w, 4, label)
        pdf.set_xy(x, pdf.get_y() + 4)
        pdf.set_font(fb, "B", 9)
        pdf.set_text_color(*_COLOR_TEXT)
        pdf.cell(col_w, 4, value)
        pdf.set_xy(x + col_w, pdf.get_y() - 4)
    pdf.ln(10)


def _draw_kpi_row(pdf: _GeoRankPDF, fn: str, fb: str, kpis: list[tuple[str, str]]):
    """Draw KPI cards as a row of large numbers with labels."""
    bar_w = pdf.w - pdf.l_margin - pdf.r_margin
    col_w = bar_w / len(kpis)
    y_start = pdf.get_y()
    for i, (label, value) in enumerate(kpis):
        x = pdf.l_margin + i * col_w
        # Value
        pdf.set_xy(x, y_start)
        pdf.set_font(fb, "B", 22)
        pdf.set_text_color(*_COLOR_KPI_VALUE)
        pdf.cell(col_w, 12, value, align="C")
        # Label
        pdf.set_xy(x, y_start + 12)
        pdf.set_font(fn, "", 9)
        pdf.set_text_color(*_COLOR_META_FG)
        pdf.cell(col_w, 6, label, align="C")
    pdf.set_y(y_start + 22)
    pdf.ln(4)


def _draw_table_header(pdf: _GeoRankPDF, fb: str, headers: list[str], col_widths: list[float], row_h: float = 7):
    """Draw table header row with dark background."""
    pdf.set_font(fb, "B", 8)
    pdf.set_fill_color(*_COLOR_HEADER_BG)
    pdf.set_text_color(*_COLOR_HEADER_FG)
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], row_h, f" {h}", border=1, fill=True)
    pdf.ln()
    pdf.set_text_color(*_COLOR_TEXT)


def _measure_cell_height(w: float, h: float, text: str, font: str, font_size: float) -> float:
    """Measure the actual height a multi_cell would need."""
    tmp = FPDF(orientation='L', format='A4')
    tmp.add_page()
    # Register CJK font if needed
    if font not in ("Helvetica", "Courier", "Times", "Symbol", "ZapfDingbats") and os.path.exists(_FONT_PATH):
        tmp.add_font(font, "", _FONT_PATH, uni=True)
    tmp.set_font(font, '', font_size)
    tmp.set_xy(0, 0)
    tmp.multi_cell(w, h, text or "", new_x='LEFT', new_y='NEXT')
    return tmp.get_y()


def _draw_table_row(pdf: _GeoRankPDF, fn: str, row: list[str], col_widths: list[float],
                    row_h: float = 7, row_idx: int = 0, font_size: float = 7.5):
    """Draw a table data row with auto-wrapping for long text."""
    pdf.set_font(fn, "", font_size)
    str_row = [str(v) for v in row]

    # Measure max height across all columns
    max_h = row_h
    for i, val in enumerate(str_row):
        h = _measure_cell_height(col_widths[i], row_h, val, fn, font_size)
        max_h = max(max_h, h)

    y0 = pdf.get_y()

    # Draw background + border rectangles
    if row_idx % 2 == 1:
        pdf.set_fill_color(*_COLOR_ROW_ALT)
    else:
        pdf.set_fill_color(255, 255, 255)
    x = pdf.l_margin
    for w in col_widths:
        pdf.set_xy(x, y0)
        pdf.cell(w, max_h, '', border=1, fill=True, new_x='LEFT', new_y='TOP')
        x += w

    # Draw text with wrapping
    pdf.set_text_color(*_COLOR_TEXT)
    x = pdf.l_margin
    for i, val in enumerate(str_row):
        pdf.set_xy(x, y0)
        pdf.multi_cell(col_widths[i], row_h, val, new_x='LEFT', new_y='TOP')
        x += col_widths[i]

    pdf.set_y(y0 + max_h)


def _draw_section_title(pdf: _GeoRankPDF, fb: str, title: str):
    """Draw a section title with bottom border."""
    pdf.set_font(fb, "B", 12)
    pdf.set_text_color(*_COLOR_TEXT)
    bar_w = pdf.w - pdf.l_margin - pdf.r_margin
    pdf.cell(bar_w, 10, title, new_x="LMARGIN", new_y="NEXT")
    # Draw underline
    pdf.set_draw_color(*_COLOR_BORDER)
    pdf.set_line_width(0.3)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(3)


# ─── CSV: Visibility Report ───────────────────────────────────────────────────

def export_csv(reports: list, brand_name: str, lang: str = "en") -> StreamingResponse:
    output = io.StringIO()
    w = csv.writer(output)

    # Metadata header
    w.writerow([_L(lang, "report_type"), _L(lang, "type_visibility")])
    w.writerow([_L(lang, "brand"), brand_name])
    w.writerow([_L(lang, "generated_at"), _now_str()])
    w.writerow([_L(lang, "total_checks"), len(reports)])
    w.writerow([])

    # Data header
    w.writerow([
        _L(lang, "engine"),
        _L(lang, "query"),
        _L(lang, "mentioned"),
        _L(lang, "position"),
        _L(lang, "word_count"),
        _L(lang, "score"),
        _L(lang, "citation"),
        _L(lang, "checked_at"),
    ])
    yes_label = _L(lang, "yes")
    no_label = _L(lang, "no")
    for r in reports:
        w.writerow([
            r.engine,
            r.query,
            yes_label if r.mentioned else no_label,
            r.position or "",
            r.word_count or "",
            r.visibility_score,
            r.citation_text or "",  # No truncation
            r.checked_at.strftime("%Y-%m-%d %H:%M") if r.checked_at else "",
        ])
    output.seek(0)
    return _csv_response(output.getvalue(), f"{brand_name}_reports.csv")


# ─── PDF: Visibility Report ───────────────────────────────────────────────────

def export_pdf(reports: list, brand_name: str, analytics: dict, lang: str = "en") -> StreamingResponse:
    pdf, fn, fb = _init_pdf(lang, "L")

    # Title
    pdf.set_font(fb, "B", 18)
    pdf.set_text_color(*_COLOR_TEXT)
    pdf.cell(0, 12, f"{_L(lang, 'report_title')} — {brand_name}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    # Metadata bar
    _draw_metadata_bar(pdf, fn, fb, [
        (_L(lang, "brand"), brand_name),
        (_L(lang, "report_type"), _L(lang, "type_visibility")),
        (_L(lang, "generated_at"), _now_str()),
        (_L(lang, "total_checks"), str(len(reports))),
    ])

    # KPI row
    _draw_kpi_row(pdf, fn, fb, [
        (_L(lang, "total_checks"), str(analytics.get("total_checks", 0))),
        (_L(lang, "mention_rate"), f"{analytics.get('mention_rate', 0)}%"),
        (_L(lang, "avg_score"), str(analytics.get("avg_score", 0))),
        (_L(lang, "trend"), str(analytics.get("trend", 0))),
    ])

    # Detail table
    _draw_section_title(pdf, fb, _L(lang, "reports"))
    col_widths = [28, 60, 22, 18, 18, 18]
    _draw_table_header(pdf, fb, [
        _L(lang, "engine"),
        _L(lang, "query"),
        _L(lang, "mentioned"),
        _L(lang, "position"),
        _L(lang, "word_count"),
        _L(lang, "score"),
    ], col_widths)

    yes_label = _L(lang, "yes")
    no_label = _L(lang, "no")
    for idx, r in enumerate(reports):
        _draw_table_row(pdf, fn, [
            r.engine,
            r.query or "",
            yes_label if r.mentioned else no_label,
            str(r.position or "-"),
            str(r.word_count or "-"),
            str(r.visibility_score),
        ], col_widths, row_idx=idx)

    # Citation section
    pdf.ln(6)
    _draw_section_title(pdf, fb, _L(lang, "citations"))
    pdf.set_font(fn, "", 8)
    for idx, r in enumerate(reports, 1):
        if not r.citation_text:
            continue
        label = f"[{idx}] {r.engine} | {r.query or ''}"
        pdf.set_font(fb, "B", 8)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 6, label, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(fn, "", 8)
        _safe_multi_cell(pdf, 0, 5, r.citation_text or "")
        pdf.ln(2)

    pdf_bytes = bytes(pdf.output())
    return StreamingResponse(
        iter([pdf_bytes]),
        media_type="application/pdf",
        headers={"Content-Disposition": _content_disposition(f"{brand_name}_report.pdf")},
    )


# ─── CSV: Statistical Analysis ────────────────────────────────────────────────

def export_statistical_csv(results: list, summary: dict, brand_name: str, lang: str = "en") -> StreamingResponse:
    output = io.StringIO()
    w = csv.writer(output)

    # Metadata header
    w.writerow([_L(lang, "report_type"), _L(lang, "type_statistical")])
    w.writerow([_L(lang, "brand"), brand_name])
    w.writerow([_L(lang, "generated_at"), _now_str()])
    w.writerow([_L(lang, "sample_count"), results[0].get("total_samples", 0) if results else 0])
    w.writerow([])

    # Summary section
    w.writerow([_L(lang, "summary")])
    w.writerow([_L(lang, "total_queries"), summary.get("total_queries", 0)])
    w.writerow([_L(lang, "overall_mention_rate"), f"{summary.get('overall_mention_rate', 0)}%"])
    w.writerow([_L(lang, "overall_avg_score"), summary.get("overall_avg_score", 0)])
    w.writerow([_L(lang, "engine_consistency"), f"{summary.get('engine_consistency', 0)}%"])
    w.writerow([])

    # Engine summary
    w.writerow([_L(lang, "engine_summary")])
    w.writerow([_L(lang, "engine"), _L(lang, "mention_rate"), _L(lang, "avg_score")])
    for engine, stats in summary.get("engine_summary", {}).items():
        w.writerow([engine, f"{stats.get('mention_rate', 0)}%", stats.get("avg_score", 0)])
    w.writerow([])

    # Detailed results
    w.writerow([_L(lang, "reports")])
    w.writerow([
        _L(lang, "engine"),
        _L(lang, "query"),
        _L(lang, "mention_count"),
        _L(lang, "total_samples"),
        _L(lang, "mention_rate"),
        _L(lang, "avg_position"),
        _L(lang, "avg_word_count"),
        _L(lang, "avg_score"),
        _L(lang, "citations"),
    ])
    for r in results:
        citations = r.get("citation_texts", [])
        w.writerow([
            r.get("engine", ""),
            r.get("query", ""),
            r.get("mention_count", 0),
            r.get("total_samples", 0),
            f"{r.get('mention_rate', 0)}%",
            r.get("avg_position", "-"),
            r.get("avg_word_count", "-"),
            r.get("avg_score", 0),
            " | ".join(citations) if citations else "",  # No truncation
        ])
    output.seek(0)
    return _csv_response(output.getvalue(), f"{brand_name}_analysis.csv")


# ─── PDF: Statistical Analysis ────────────────────────────────────────────────

def export_statistical_pdf(results: list, summary: dict, brand_name: str, lang: str = "en") -> StreamingResponse:
    pdf, fn, fb = _init_pdf(lang, "L")
    sample_count = results[0].get("total_samples", 0) if results else 0

    # Title
    pdf.set_font(fb, "B", 18)
    pdf.set_text_color(*_COLOR_TEXT)
    pdf.cell(0, 12, f"{_L(lang, 'analysis_title')} — {brand_name}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    # Metadata bar
    _draw_metadata_bar(pdf, fn, fb, [
        (_L(lang, "brand"), brand_name),
        (_L(lang, "report_type"), _L(lang, "type_statistical")),
        (_L(lang, "generated_at"), _now_str()),
        (_L(lang, "sample_count"), str(sample_count)),
    ])

    # KPI row
    _draw_kpi_row(pdf, fn, fb, [
        (_L(lang, "total_queries"), str(summary.get("total_queries", 0))),
        (_L(lang, "overall_mention_rate"), f"{summary.get('overall_mention_rate', 0)}%"),
        (_L(lang, "overall_avg_score"), str(summary.get("overall_avg_score", 0))),
        (_L(lang, "engine_consistency"), f"{summary.get('engine_consistency', 0)}%"),
    ])

    # Engine summary table
    _draw_section_title(pdf, fb, _L(lang, "engine_summary"))
    ew = [50, 50, 50]
    _draw_table_header(pdf, fb, [
        _L(lang, "engine"), _L(lang, "mention_rate"), _L(lang, "avg_score"),
    ], ew)
    for idx, (engine, stats) in enumerate(summary.get("engine_summary", {}).items()):
        _draw_table_row(pdf, fn, [
            engine,
            f"{stats.get('mention_rate', 0)}%",
            str(stats.get("avg_score", 0)),
        ], ew, row_idx=idx, font_size=9)

    pdf.ln(6)

    # Detailed results table
    _draw_section_title(pdf, fb, _L(lang, "reports"))
    cw = [25, 50, 20, 20, 20, 20, 20, 20]
    _draw_table_header(pdf, fb, [
        _L(lang, "engine"),
        _L(lang, "query"),
        _L(lang, "mention_count"),
        _L(lang, "total_samples"),
        _L(lang, "mention_rate"),
        _L(lang, "avg_position"),
        _L(lang, "avg_word_count"),
        _L(lang, "avg_score"),
    ], cw)

    for idx, r in enumerate(results):
        _draw_table_row(pdf, fn, [
            r.get("engine", ""),
            r.get("query", "") or "",
            str(r.get("mention_count", 0)),
            str(r.get("total_samples", 0)),
            f"{r.get('mention_rate', 0)}%",
            str(r.get("avg_position", "-")),
            str(r.get("avg_word_count", "-")),
            str(r.get("avg_score", 0)),
        ], cw, row_idx=idx)

    # Citation section
    pdf.ln(6)
    _draw_section_title(pdf, fb, _L(lang, "citations"))
    for idx, r in enumerate(results, 1):
        citations = r.get("citation_texts", [])
        if not citations:
            continue
        label = f"[{idx}] {r.get('engine', '')} | {r.get('query', '')}"
        pdf.set_font(fb, "B", 8)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 6, label, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(fn, "", 8)
        for citation in citations:
            _safe_multi_cell(pdf, 0, 5, citation or "")
        pdf.ln(2)

    pdf_bytes = bytes(pdf.output())
    return StreamingResponse(
        iter([pdf_bytes]),
        media_type="application/pdf",
        headers={"Content-Disposition": _content_disposition(f"{brand_name}_analysis.pdf")},
    )
